url: "https://jamesholehouse.github.io" # Replace with your actual URL
baseurl: "" # Keep this empty if the site is at the root of the domain
title: "James Holehouse"
description: "Stochasticity and Complexity"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true
  syntax_highlighter_opts:
    block: "<div class=\"highlight\"><pre class=\"highlight\"><code>"
    span: "<span class=\"code\">"
    line_number_start: 1
    line_numbers: false
    line_number_anchors: false

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .jekyll-cache
  - .jekyll-metadata

# Include folders with images
include:
  - assets
  - images
  - _posts

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
