menu:
#- {name: 'people', url: '/people'}
- {name: 'Publications', url: '/publications'}
- {name: 'talks', url: '/talks'}
# - {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

# people:
# - {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
# - {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
# - {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

# talks:
# - {name: 'Vector Calculus', url: 'vector-calculus'}
# - {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
# - {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/jamesholehouse'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/james-holehouse-phd/'}
- {icon: 'google', link: 'https://scholar.google.com/citations?user=mNYEw90AAAAJ&hl=en'}

contacts:
- {name: 'Dr. James Holehouse', title: 'Postdoctoral researcher', institution: 'The Santa Fe Institute', institution_address: '1399 Hyde Park Rd, Santa Fe, NM 87501, United States', email: 'jamesholehouse1@gmail.com or jamesholehouse@santafe.edu', office: 'SFI Cowan Campus, Pod C', image: 'assets/img/me.jpg'}
